### ISSUE TITLE
Mise en place de la structure BACK

### ISSUE THREAD

**Issue by matdn** [IIM-Creative-Technology/Canaries#2]

**Comment by AntoineBendafiSchulmann** [comment]
consultez le code qui seras présent dans server.js
ainsi que ce qu'est redis ( C'est une sorte de base de donnée utilisant pas mal de système dont ici le cache)

**Comment by AntoineBendafiSchulmann** [comment]
à faire : questions du bot. réponses du bot

réalisé : chat avec canaux

**Comment by AntoineBendafiSchulmann** [comment]
stock des tableau de données , (formatés dans les messages.js et users.js dans le cache

**Comment by AntoineBendafiSchulmann** [comment]
inscrire le nom du joueur

**Comment by AntoineBendafiSchulmann** [comment]
le nom du joueur est inscrit mtn
